### ISSUE TITLE
How to you balance your side projects?

### ISSUE THREAD

**Issue by wesbos** [darrinhenein/ama#1]
With a full time job at Mozilla, a kid, a commute and what I'm sure is a very full life. How do you find time for side projects? When do you work on them? How do you balance that with your family?

**Comment by darcyclarke** [comment]
:+1:

**Comment by wesbos** [comment]
:+1:  (apparently by not wasting time on AMAs)

**Comment by darrinhenein** [comment]
This is actually something I've been asked before, and often. I think partially because I seem to create the illusion that I'm far more industrious than I actually am, and partially I guess because, well, I like to keep myself busy!

The easiest answer is that the best way to balance your side projects is to not leave yourself any balancing to do (is this cheating?). I really value _focus_, and try my hardest to limit the number of things I'm working on. If you're only working on one thing at a time, the balancing act becomes much simpler.

I keep very strict rules: for example, I allow myself to read only 2 books at any time; one fiction and one non-fiction. To start a new book, I must finish (or abandon) one of the current ones. This helps me stay motivated (I can't wait to read the next thing!) and forces me to continually re-evaluate what I'm spending my time on: if I'm not enjoying something, why bother finishing it? No one is paying me to read this book, so it should (primarily) be about enjoyment.

Also, take baby steps. Long books can be overwhelming. Rather than focus on the sheer weight of the book in your hand, focus on just getting through the first 10 pages. Then the next 10. The book make take you weeks or months to finish, but anyone can read for 5 minutes. Eventually, you'll get somewhere.

That was mostly about reading books, but the same principles apply to getting side-projects done: maintain focus, be diligent about distractions and getting sidetracked, and take big things and attack them in tiny, tiny pieces.

As far as balancing side projects with a full-time job or family, it just comes down to what's important to you. Making and finishing _Lastronaut_ was really important to me, so I stayed up late working instead of watching TV. Everyone gets 24 hours each day. Spend it on what's important.

Also, what @wesbos [said](https://github.com/darrinhenein/ama/issues/1#issuecomment-120495843) ;)
