### ISSUE TITLE
How did you get into making games?

### ISSUE THREAD

**Issue by sindresorhus** [darrinhenein/ama#6]
[Lastronaut](http://www.lastronautgame.com/) looks really cool btw :)

**Comment by darrinhenein** [comment]
This is a tough one, as I really have only ever shipped one game. It’s also something I was never taught to do, so I just went about it in my own way. I guess the real answer is “slowly”: as I learned to write code and became fluent in more languages, I naturally started exploring the realm of “creative coding”… where rather than generate a web page or solve some specific problem, the focus is on creating generative, computer aided artwork. 

I started exploring frameworks like [Processing](https://processing.org/), [OpenFrameworks](http://www.openframeworks.cc/), and HTML5 with WebGL and the canvas. I was writing little experiments… code that randomly generated a believable island ecosystem, or programs that would visualize the language used across twitter to predict trending topics. 

As someone who grew up admiring and idolizing the genius of videos games, it was always something I wished I could do. To combine writing, artwork, motion design, sound and music composition with gameplay logic and programming seemed like a mighty task–albeit one that (occasionally) produced stunning works of multimedia art.

As a crayon and guitar wielding youth, the programming was the last piece of the puzzle to fit in, and believing I had (at least some of!) the requisite skills, I just started making a game. It took me two years with help from a friend, and I probably learned most of it along the way, but resolved to finish it, I hacked my way to a finished product. 

I guess my advice to anyone wanting to make a game would be to just go make one… no book or tutorial will prepare you for what you’ll learn along the way.
