### ISSUE TITLE
What was your best programming moment?

### ISSUE THREAD

**Issue by sindresorhus** [darrinhenein/ama#7]

**Comment by darrinhenein** [comment]
I was getting into machine learning and computer vision stuff a few years ago, and had this crazy idea of making an app that when shown a spread from a "Where’s Waldo" book, would find him and draw a circle at his location.

Getting that to work (which certainly less code and of less complexity than other things I’ve since done), seemed like pure old-fashioned magic.

Finishing [Lastronaut](http://lastronautgame.com) would be up there too, and was easily the biggest project I’ve ever finished.
